package edu.northeastern.cs5500.starterbot.command;

import edu.northeastern.cs5500.starterbot.controller.CartController;
import java.util.Objects;
import javax.annotation.Nonnull;
import javax.inject.Inject;
import javax.inject.Singleton;
import net.dv8tion.jda.api.events.interaction.command.SlashCommandInteractionEvent;
import net.dv8tion.jda.api.events.interaction.component.ButtonInteractionEvent;
import net.dv8tion.jda.api.interactions.commands.build.CommandData;
import net.dv8tion.jda.api.interactions.commands.build.Commands;

@Singleton
public class CartCommand implements SlashCommandHandler, ButtonHandler {

    @Inject CartController cartController;
    @Inject CartRender cartRender;
    @Inject MenuRender menuRender;
    @Inject CheckoutRender checkoutRender;
    @Inject DeleteCommand deleteCommand;

    @Inject
    public CartCommand() {
        // left blank for Dagger injection
    }

    /** The name of this class. */
    @Override
    @Nonnull
    public String getName() {
        return "cart";
    }

    /** The description of this command. */
    @Override
    @Nonnull
    public CommandData getCommandData() {
        return Commands.slash(getName(), "Display all dishes added to the cart.");
    }

    /** Send cart to the customer. */
    @Override
    public void onSlashCommandInteraction(@Nonnull SlashCommandInteractionEvent event) {
        String discordUserId = event.getUser().getId();
        cartRender.renderCart(event.getHook(), discordUserId);
    }

    /**
     * This function is to make interaction with customers. If they chose Add More, they will be
     * shown the menu. If they chose Delete, they can delete one dish at a time. If they chose
     * Checkout, they can make payment for their dishes in their cart. If they chose cancel, they
     * can exit this store, and their cart will be clear.
     */
    @Override
    public void onButtonInteraction(@Nonnull ButtonInteractionEvent event) {
        final String id = Objects.requireNonNull(event.getButton().getId());
        final String response = id.split(":")[1];
        event.deferReply()
                .queue(); // Only this sentence is generated by ChatGPT using OpenAI GPT-3.5 model,
        // version 2021-09
        switch (response) {
            case "add-more":
                menuRender.renderMenu(event.getHook());
                break;
            case "delete":
                deleteCommand.sendDelete(event);
                break;
            case "checkout":
                checkoutRender.renderCheckout(event.getHook(), event.getUser().getId());
                break;
            case "cancel":
                clearCart(event);
                break;
            default:
                event.getHook().sendMessage("Invalid option selected.").queue();
        }
    }

    /**
     * Menu can be sent when somebody clicked a button.
     *
     * @param event The interaction we got from button
     */
    public void sendCart(@Nonnull ButtonInteractionEvent event) {
        String discordUserId = event.getUser().getId();
        cartRender.renderCart(event.getHook(), discordUserId);
    }

    /**
     * Menu can be cleared after user have maken payment or exit the store.
     *
     * @param event The interaction we got from button
     */
    public void clearCart(ButtonInteractionEvent event) {
        String discordUserId = event.getUser().getId();
        cartController.clearCart(discordUserId);
        event.getHook()
                .sendMessage("Your cart has been cleared. Thanks for visiting FoodiePanda.")
                .queue();
    }
}
