package edu.northeastern.cs5500.starterbot.command;

import edu.northeastern.cs5500.starterbot.controller.CartController;
import edu.northeastern.cs5500.starterbot.model.Cart;
import java.util.Objects;
import javax.annotation.Nonnull;
import javax.inject.Inject;
import javax.inject.Singleton;
import lombok.extern.slf4j.Slf4j;
import net.dv8tion.jda.api.EmbedBuilder;
import net.dv8tion.jda.api.events.interaction.command.SlashCommandInteractionEvent;
import net.dv8tion.jda.api.events.interaction.component.ButtonInteractionEvent;
import net.dv8tion.jda.api.interactions.commands.build.CommandData;
import net.dv8tion.jda.api.interactions.commands.build.Commands;
import net.dv8tion.jda.api.interactions.components.buttons.Button;
import net.dv8tion.jda.api.utils.messages.MessageCreateBuilder;

@Singleton
@Slf4j
public class CheckoutCommand implements SlashCommandHandler, ButtonHandler {

    @Inject CartCommand cartCommand;
    @Inject CongraCommand congraCommand;
    @Inject CartController cartController;
    @Inject CheckoutRender checkoutRender;

    @Inject
    public CheckoutCommand() {
        // left blank for Dagger injection
    }

    /** The name of this class. */
    @Override
    @Nonnull
    public String getName() {
        return "checkout";
    }

    /** The description of this command. */
    @Override
    @Nonnull
    public CommandData getCommandData() {
        return Commands.slash(getName(), "Please checkout here."); // Changed command description
    }

    /**
     * Showing the total price of dishes in customers' cart. They can make payment by clicking Make
     * Payment button. They can go back to their cart by clicking Back to Cart. They can clear their
     * cart and exit by clickng Cancel.
     *
     * @param event the interaction from user
     */
    @Override
    public void onSlashCommandInteraction(@Nonnull SlashCommandInteractionEvent event) {
        log.info("event: /checkout");

        String discordUserId = event.getUser().getId();
        Cart cart = cartController.getCartForUser(discordUserId);
        EmbedBuilder embedBuilder =
                new EmbedBuilder()
                        .setTitle("Total Price: " + String.format("$%.2f", cart.getTotalPrice()));

        MessageCreateBuilder messageCreateBuilder = new MessageCreateBuilder();
        messageCreateBuilder =
                messageCreateBuilder.addActionRow(
                        Button.primary(this.getName() + ":make-payment", "Make Payment"),
                        Button.primary(this.getName() + ":cart", "Back to Cart"),
                        Button.danger(this.getName() + ":cancel", "Cancel"));

        messageCreateBuilder.setContent("").setEmbeds(embedBuilder.build());
        event.reply(messageCreateBuilder.build()).queue();
    }

    /**
     * This function is to make interaction with customers. If they chose "Make Payment", they can
     * pay for their cart. If they chose "Back to Cart", they will be shown their cart. If they
     * chose "Cancel", they can exit this store, and their cart will be clear.
     */
    @Override
    public void onButtonInteraction(@Nonnull ButtonInteractionEvent event) {
        final String response = Objects.requireNonNull(event.getButton().getId()).split(":")[1];
        Objects.requireNonNull(response);

        event.deferReply()
                .queue(); // Only this sentence is generated by ChatGPT using OpenAI GPT-3.5 model,
        // version 2021-09

        switch (response) {
            case "make-payment":
                congraCommand.sendCongra(event);
                break;
            case "cart":
                cartCommand.sendCart(event);
                break;
            case "cancel":
                cartCommand.clearCart(event);
                break;
            default:
                event.getHook().sendMessage("Invalid option selected.").queue();
        }
    }

    /**
     * Send customer the checkout message.
     *
     * @param event
     */
    public void sendCheckout(@Nonnull ButtonInteractionEvent event) {
        String discordUserId = event.getUser().getId();
        checkoutRender.renderCheckout(event.getHook(), discordUserId);
    }
}
