package edu.northeastern.cs5500.starterbot.command;

import java.util.Objects;
import javax.annotation.Nonnull;
import javax.inject.Inject;
import javax.inject.Singleton;
import lombok.extern.slf4j.Slf4j;
import net.dv8tion.jda.api.EmbedBuilder;
import net.dv8tion.jda.api.events.interaction.command.SlashCommandInteractionEvent;
import net.dv8tion.jda.api.events.interaction.component.ButtonInteractionEvent;
import net.dv8tion.jda.api.interactions.InteractionHook;
import net.dv8tion.jda.api.interactions.commands.build.CommandData;
import net.dv8tion.jda.api.interactions.commands.build.Commands;
import net.dv8tion.jda.api.interactions.components.buttons.Button;

@Singleton
@Slf4j
public class DeliveryCommand implements SlashCommandHandler, ButtonHandler {
    @Inject MenuCommand menuCommand;

    @Inject
    public DeliveryCommand() {
        // left blank for Dagger injection
    }

    /** The name of this class. */
    @Override
    @Nonnull
    public String getName() {
        return "deliver";
    }

    /** The description of this command. */
    @Override
    @Nonnull
    public CommandData getCommandData() {
        return Commands.slash(getName(), "Deliver your order.");
    }

    /**
     * Showing that the order has been delivered. Customer can also Place a new order or exit the
     * store.
     *
     * @param hook
     */
    private void display(@Nonnull InteractionHook hook) {
        log.info("event: /deliver");

        EmbedBuilder embedBuilder = new EmbedBuilder();
        embedBuilder.setTitle("Your order is delivered.");

        hook.sendMessageEmbeds(embedBuilder.build())
                .addActionRow(
                        Button.primary(getName() + ":menu", "Place new order"),
                        Button.danger(getName() + ":exit", "Exit"))
                .setEphemeral(true)
                .queue();
    }

    /**
     * If Customer chose "Place new order", he will be shown the menu. If he chose "Exit", he will
     * exit the store.
     */
    @Override
    public void onButtonInteraction(@Nonnull ButtonInteractionEvent event) {
        final String id = Objects.requireNonNull(event.getButton().getId());
        final String response = id.split(":")[1];
        Objects.requireNonNull(response);
        event.deferReply()
                .queue(); // Only this sentence is generated by ChatGPT using OpenAI GPT-3.5 model,
        // version 2021-09
        switch (response) {
            case "menu":
                menuCommand.sendMenu(event);
                break;
            case "exit":
                event.getHook().sendMessage("Thanks for your order. See you next time!").queue();
                break;
            default:
                event.getHook().sendMessage("Invalid option selected.").queue();
        }
    }

    /** Show the delivery message to customers. */
    @Override
    public void onSlashCommandInteraction(@Nonnull SlashCommandInteractionEvent event) {
        display(event.getHook());
    }

    /** Show the delivery message to customers. */
    public void sendDeliver(@Nonnull ButtonInteractionEvent event) {
        display(event.getHook());
    }
}
