package edu.northeastern.cs5500.starterbot.model;

import lombok.Data;
import org.bson.types.ObjectId;

@Data
public class Dish {
    private String dishName;
    private double price;
    ObjectId id;

    public Dish(String dishName, double price) {
        this.dishName = dishName;
        this.price = price;
    }

    // All codes below are redundant, since they are generated by @Data

    // public String getDishName() {
    //     return name;
    // }

    // public double getPrice() {
    //     return price;
    // }

    // @Override
    // public boolean equals(Object addedDish) {
    //     if (this == addedDish) {
    //         return true;
    //     }
    //     if (addedDish == null || getClass() != addedDish.getClass()) {
    //         return false;
    //     }
    //     Dish dish = (Dish) addedDish;
    //     return Double.compare(dish.price, price) == 0 && Objects.equals(name, dish.name);
    // }

    // @Override
    // public int hashCode() {
    //     return Objects.hash(name, price);
    // }
}
